### ISSUE TITLE
Embedding mismatch when trying to run ESIM on MNLI

### ISSUE THREAD

**Issue by aalok-sathe** [woollysocks/multiNLI#14]
I tried to run the code out-of-the-box, no modification, and here's what I run into:

`Traceback (most recent call last):
  File "train_mnli.py", line 73, in <module>
    loaded_embeddings = loadEmbedding_rand(FIXED_PARAMETERS["embedding_data_path"], word_indices)
  File "../multiNLI/python/util/data_processing.py", line 146, in loadEmbedding_rand
    emb[word_indices[s[0]], :] = np.asarray(s[1:])
ValueError: could not broadcast input array from shape (302) into shape (300)`

I was wondering if I'm overlooking any obvious steps, or whether someone else has faced this before, or whether it has something to do with updates to GLoVE that the code has not kept up with. Any insights will be appreciated, and if you have any pointers I'll try to PR a fix.

**Comment by aalok-sathe** [comment]
I just noticed such a PR (#12) already exists, just hasn't been merged. I suppose I'll close this, and use that fork instead.
